name: Pipeline CI/CD
#Nome de execução da pipeline
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

#Disparando a exec usando ON.
on:
#Executando manualmente precisa usar o workflow_dispatch
  workflow_dispatch:
#Colando o evento que vai disparar o workflow
  push:
    branches:
      - main
        
#Especifique os conjuntos de instruções, jobs.1
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest #agente de execução em ambiente
    steps: #passos executados #declarando o ambiente
      - name: Obtendo o código do projeto 
        uses: actions/checkout@v4
      - name: setup do projeto
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: "8.0.300"
      - name: Executando o comando build
        working-director: ./src
        run: dotnet build review ReviewFilmes.sln
          
